Repository deco-cx/apps, pull requests merged in 2023-09, with the labels that each got.

#39 Add a matcher to negate a matcher.
  commerce/manifest.gen.ts
  compat/$live/manifest.gen.ts
  compat/std/manifest.gen.ts
  decohub/manifest.gen.ts
  shopify/handlers/sitemap.ts
  shopify/manifest.gen.ts
  vnda/manifest.gen.ts
  vtex/manifest.gen.ts
  vtex/utils/batch.ts
  website/manifest.gen.ts
  website/matchers/negate.ts
  workflows/manifest.gen.ts
Labels: enhancement

#41 Add missing VTEX catalog filters URL on categories and search
  vtex/utils/transform.ts
  website/components/_Controls.tsx
Labels: bug

#45 Cep vnda pdp & start.ts FIX
  compat/$live/manifest.gen.ts
  compat/std/manifest.gen.ts
  decohub/manifest.gen.ts
  scripts/start.ts
  shopify/manifest.gen.ts
  vnda/actions/cart/simulation.ts
  vnda/hooks/useCart.ts
  vnda/manifest.gen.ts
  vnda/utils/client/client.ts
  vnda/utils/client/types.ts
  vnda/utils/openapi/vnda.openapi.gen.ts
  vnda/utils/openapi/vnda.openapi.json
  vtex/manifest.gen.ts
  wake/manifest.gen.ts
  website/manifest.gen.ts
  workflows/manifest.gen.ts
Labels: bug, enhancement

#64 feat: Algolia + Typesense Integration
  README.md
  admin/manifest.gen.ts
  algolia/README.md
  algolia/actions/index/product.ts
  algolia/actions/index/wait.ts
  algolia/loaders/productList.ts
  algolia/loaders/productListingPage.ts
  algolia/manifest.gen.ts
  algolia/mod.ts
  algolia/utils/highlight.ts
  algolia/utils/product.ts
  algolia/workflows/index/product.ts
  commerce/manifest.gen.ts
  compat/$live/manifest.gen.ts
  compat/std/manifest.gen.ts
  deco.ts
  decohub/apps/algolia.ts
  decohub/apps/typesense.ts
  decohub/manifest.gen.ts
  deno.json
  scripts/start.ts
  shopify/manifest.gen.ts
  typesense/README.md
  typesense/actions/index/product.ts
  typesense/fly.toml
  typesense/loaders/productList.ts
  typesense/loaders/productListingPage.ts
  typesense/manifest.gen.ts
  typesense/mod.ts
  typesense/utils/highlight.ts
  typesense/utils/once.ts
  typesense/utils/product.ts
  typesense/workflows/index/product.ts
  utils/fetch.ts
  vnda/manifest.gen.ts
  vtex/actions/masterdata/createDocument.ts
  vtex/actions/trigger.ts
  vtex/loaders/intelligentSearch/productListingPage.ts
  vtex/loaders/product.ts
  vtex/manifest.gen.ts
  vtex/mod.ts
  vtex/utils/transform.ts
  vtex/utils/vtex.openapi.gen.ts
  vtex/utils/vtex.openapi.json
  vtex/workflows/events.ts
  wake/manifest.gen.ts
  website/manifest.gen.ts
  website/mod.ts
  website/utils/unhandledRejection.ts
  workflows/manifest.gen.ts
Labels: enhancement
