Repository deco-cx/apps, pull requests merged in 2024-09, with the labels that each got.

#832 Refactoring Linx duplicated types
  linx/utils/transform.ts
  linx/utils/types/auctionDetailJSON.ts
  linx/utils/types/auctionJSON.ts
  linx/utils/types/basket.ts
  linx/utils/types/basketJSON.ts
  linx/utils/types/common.ts
  linx/utils/types/facets.ts
  linx/utils/types/gridProductsJSON.ts
  linx/utils/types/login.ts
  linx/utils/types/newsletterJSON.ts
  linx/utils/types/productByIdJSON.ts
  linx/utils/types/productJSON.ts
  linx/utils/types/productList.ts
  linx/utils/types/shared.ts
  linx/utils/types/suggestionsJSON.ts
Labels: work in progress

#837 Allow users to specify search params on route path
  website/handlers/router.ts
Labels: website

#851 fix(shopify): add `filters` to productListingPage cacheKey
  shopify/loaders/ProductListingPage.ts
Labels: needs review
