Repository deco-cx/apps, pull requests merged in 2024-03, with the labels that each got.

#443 fix: Preview fetched when imported
  decohub/apps/algolia.ts
  decohub/apps/implementation.ts
  decohub/apps/linx.ts
  decohub/apps/shopify.ts
  decohub/apps/sourei.ts
  decohub/apps/typesense.ts
  decohub/apps/vnda.ts
  decohub/apps/wake.ts
Labels: ready to merge

#442 [ Vnda ] - PriceRange
  vnda/loaders/productListingPage.ts
Labels: ready to merge

#441 Wap Proxy and PLP filters and sort
  wap/loaders/productListingPage.ts
  wap/loaders/proxy.ts
  wap/utils/openapi/api.openapi.gen.ts
  wap/utils/openapi/api.openapi.json
Labels: needs review

#439 feat(website/commerce): Add seo property for pages and PDP/PLP section preview
  commerce/manifest.gen.ts
  commerce/mod.ts
  commerce/sections/Seo/SeoPDP.tsx
  commerce/sections/Seo/SeoPDPV2.tsx
  commerce/sections/Seo/SeoPLP.tsx
  commerce/sections/Seo/SeoPLPV2.tsx
  compat/std/sections/SEOPDP.tsx
  compat/std/sections/SEOPLP.tsx
  website/Preview.tsx
  website/components/Seo.tsx
  website/manifest.gen.ts
  website/mod.ts
  website/pages/Page.tsx
  website/sections/Seo/Seo.tsx
  website/sections/Seo/SeoV2.tsx
Labels: website, admin

#455 fix(google-fonts): Sort and filter duplicated font variations
  website/loaders/fonts/googleFonts.ts
Labels: ready to merge

#459 Removing pagination in filter urls in VNDA
  vnda/utils/transform.ts
Labels: ready to merge

#440 [ SEO | VTEX ] Add meta robots in SEO PLP and SEO PDP
  commerce/sections/Seo/SeoPLP.tsx
  commerce/sections/Seo/SeoPLPV2.tsx
  vtex/loaders/legacy/productDetailsPage.ts
  vtex/utils/legacy.ts
  website/components/Seo.tsx
Labels: vtex, needs review
